[package]
name = "srv"
version = "0.1.0"
authors = ["danloh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.1.29"
actix = "0.8.3"
actix-rt = "0.2.5"
actix-http = "0.2.10"
actix-web = "1.0.8"
actix-cors = "0.1.0"
diesel = { version = "1.4.3", features = ["postgres","chrono","serde_json","uuidv07","r2d2"] }
r2d2 = "0.8.6"
serde_derive = "1.0.102"
serde_json = "1.0.41"
serde = "1.0.102"

jsonwebtoken = "6.0.1"
lettre = "0.9"
lettre_email = "0.9"
oauth2 = "=1.3.0"
rand = "0.7"

derive_more = "0.15.0"
regex = "1.3.1"
lazy_static = "1.4.0"
deunicode = "1.0.0"
bcrypt = "0.6.1"
chrono = { version = "0.4.9", features = ["serde"] }
log = "0.4.8"
fern = "0.5.9"
dotenv = "0.15.0"
base64 = "0.11.0"
num_cpus = "1.11.0"

actix-files = "0.1.6"
tera = "1.0.0-beta.18"
unic-segment = "0.9.0"

reqwest = "0.9.22"
scraper = "0.11.0"

swirl = { git = "https://github.com/sgrif/swirl.git", rev = "de5d8bb" }
parking_lot = "0.9.0"
